version: 2
jobs:
  build:
    working_directory: /go/src/github.com/favclip/genbase
    docker:
      - image: google/cloud-sdk:306.0.0
        environment:
          GOPATH: /go
          GOLANG_VERSION: 1.11.13
          GO111MODULE: "on"
    steps:
      - run:
          name: PATH update
          command: |
            echo "export PATH=\$PATH:/go/bin:/usr/local/go/bin" >> $BASH_ENV
            cat $BASH_ENV
      - run:
          name: install go binary
          command: |
            echo $PATH
            /usr/bin/curl -o go.tar.gz https://storage.googleapis.com/golang/go${GOLANG_VERSION}.linux-amd64.tar.gz && \
            tar -zxf go.tar.gz && \
            mv go /usr/local && \
            rm go.tar.gz

      - checkout

      - run: ./setup.sh
      - run: ./test.sh
